version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - custom_network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_network

  backend.messageprocessor:
    build:
      context: .
      dockerfile: src/Backend.MessageProcessor/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - custom_network

  backend.presentation.api:
    build:
      context: .
      dockerfile: src/Backend.Presentation.API/Dockerfile
    ports:
      - '5001:8080'
      - '5000:8081'
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - custom_network

volumes:
  rabbitmq_data:
  postgres_data:

networks:
  custom_network:
    driver: bridge
